/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'EN' | 'FR';

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        'nav.home': 'Home',
        'nav.profile': 'Profile',
        'nav.section': 'Section',
        'nav.about': 'About',
        'nav.contact': 'Contact',
        'nav.experience': 'Experience',
        'nav.education': 'Education',
        'nav.skills': 'Skills',
        'nav.projects': 'Projects',
        'nav.linkedin_freelancing': 'LinkedIn Freelancing',
        'nav.ai_projects': 'AI Systems & Projects',
        'nav.certifications': 'Certifications',
        'btn.download_cv': 'Download CV',

        'hero.system_mode': 'SYSTEM MODE · ACTIVE',
        'hero.title_1_p1':'I Help You Get',
        'hero.title_1_p2':'More visibility',
        'hero.title_2_p1':'Leads, and Results',
        'hero.title_2_p2':'on LinkedIn',
        'hero.subtitle': 'Build visibility, attract the right audience, and turn LinkedIn into a real growth channel.',
        'hero.ai_action': 'AI Action Line',
        'hero.ai_diff': 'Powered by smart automation and AI systems to optimize content, workflows, and decisions.',
        'hero.cta_contact': 'Contact Me',

        'linkedin.badge': 'Service Level: Premium',
        'linkedin.title': 'LinkedIn Growth System',
        'linkedin.subtitle': 'A structured framework to build visibility, authority, and growth for small businesses on LinkedIn.',
        'linkedin.strat_1_title': 'Audience Growth',
        'linkedin.strat_1_desc': 'Expanding your reach to qualified prospects and industry leaders.',
        'linkedin.strat_2_title': 'Content Strategy',
        'linkedin.strat_2_desc': 'Data-driven narrative design that positions you as a thought leader.',
        'linkedin.strat_3_title': 'Profile Optimization',
        'linkedin.strat_3_desc': 'Converting visits into meetings with high-converting copy.',
        'linkedin.strat_4_title': 'Brand Positioning',
        'linkedin.strat_4_desc': 'Strategic differentiation in a crowded digital marketplace.',
        'linkedin.step': 'Step',
        'linkedin.step_1': 'Analysis',
        'linkedin.step_2': 'Strategy',
        'linkedin.step_3': 'Execution',
        'linkedin.step_4': 'Optimization',
        'linkedin.examples_title': 'Work Examples',
        'linkedin.examples_subtitle': 'Proven strategies and real-world results from successful LinkedIn growth campaigns.',
        'linkedin.example_1_title': 'LinkedIn Content Creation',
        'linkedin.example_1_subtitle': 'LinkedIn Content Creation (Keywords & Topics)',
        'linkedin.example_1_desc': 'Creating LinkedIn content based on strategic keywords and high-demand topics, designed to maximize visibility, engagement, and organic reach.',
        'linkedin.example_1_res': '100k+ Impressions',
        'linkedin.example_2_title': 'Optimized LinkedIn Profile',
        'linkedin.example_2_subtitle': 'LinkedIn Profile Optimization (Section by Section)',
        'linkedin.example_2_desc': 'Complete LinkedIn profile optimization — headline, about, experience, and visuals — to improve clarity, credibility, and conversion.',
        'linkedin.example_2_res': 'Premium Quality',
        'linkedin.example_3_title': 'Strategic Growth & Visibility',
        'linkedin.example_3_desc': 'Audience development from 0 to 40k through a structured content strategy focused on visibility, consistency, and sustainable growth.',
        'linkedin.example_3_res': '40k+ Growth',
        'linkedin.view_cta': 'VIEW ONLY',
        'linkedin.growth_case': 'Growth Case',

        'ai.badge': 'Module: Intelligent Systems',
        'ai.title': 'AI Systems & Intelligent Agents',
        'ai.subtitle': 'Engineering technical, clean, and credible solutions through serious AI implementation.',
        'ai.cap_1': 'AI Agents',
        'ai.cap_2': 'Multi-Agent Systems',
        'ai.cap_3': 'RAG',
        'ai.cap_4': 'Machine Learning',
        'ai.cap_5': 'Automation',
        'ai.proj_prefix': 'Project',
        'ai.stack': 'Stack',

        'timeline.exp_title': 'Professional Experience',
        'timeline.edu_title': 'Education',
        'timeline.exp_1_title': 'LinkedIn Freelancer & Digital Marketing Strategist',
        'timeline.exp_1_company': 'Self-Employed',
        'timeline.exp_1_period': '2022 - Present',
        'timeline.exp_1_desc': 'Developing and executing growth strategies for B2B founders and companies.',
        'timeline.exp_2_title': 'Economic & Social Services Officer',
        'timeline.exp_2_company': 'Public Sector',
        'timeline.exp_2_period': 'Previous',
        'timeline.exp_2_desc': 'Managed administrative and strategic social operations with focus on data precision.',
        'timeline.exp_3_title': 'Internships (TGR, Banque Populaire)',
        'timeline.exp_3_company': 'Multiple Entities',
        'timeline.exp_3_period': 'Early Career',
        'timeline.exp_3_desc': 'Gained foundational experience in financial services and public treasury operations.',
        'timeline.edu_1_title': 'AI Development',
        'timeline.edu_1_school': 'JobInTech / SUPMIR Academy',
        'timeline.edu_1_period': '02-2026',
        'timeline.edu_1_desc': 'Specializing in Intelligent Agents, LLMs, and System Automation.',
        'timeline.edu_2_title': 'Bachelor’s Degree – Economics & Management',
        'timeline.edu_2_school': 'University',
        'timeline.edu_2_period': '2019',
        'timeline.edu_2_desc': 'Theoretical and practical foundation in business dynamics and economic modeling.',
        'timeline.certs_title': 'Certifications Overview',
        'timeline.cert_1': 'AI & Technology Specialist',
        'timeline.cert_2': 'Digital Marketing & Analytics',
        'timeline.cert_3': 'Professional Project Tools',

        'skills.badge': 'Core Competencies',
        'skills.title': 'Technical & Strategic Stack',
        'skills.group_1': 'Digital Marketing & LinkedIn',
        'skills.group_2': 'AI & Intelligent Systems',
        'skills.group_3': 'Technical & Project Tools',
        'skills.g1_1': 'Audience Growth',
        'skills.g1_2': 'Content Strategy',
        'skills.g1_3': 'Profile Optimization',
        'skills.g1_4': 'B2B Lead Gen',
        'skills.g1_5': 'Google Analytics',
        'skills.g2_1': 'AI Agents',
        'skills.g2_2': 'Multi-Agent Systems',
        'skills.g2_3': 'RAG & LLMs',
        'skills.g2_4': 'Machine Learning',
        'skills.g2_5': 'Workflow Automation',
        'skills.g3_1': 'Jira & Agile Method',
        'skills.g3_2': 'Strategic Planning',
        'skills.g3_3': 'Data Analysis',
        'skills.g3_4': 'Python/TypeScript',
        'skills.g3_5': 'React/Node.js',

        'about.mission_title': 'My Mission',
        'about.mission_desc': 'Help small businesses, entrepreneurs, and professionals grow their visibility and audience on LinkedIn through clear strategies, consistent execution, and smart use of automation and AI systems.',
        'about.do_title': 'What I Do for Clients',
        'about.do_1': 'Build and optimize LinkedIn profiles and company pages',
        'about.do_2': 'Create and manage content aligned with business goals',
        'about.do_3': 'Analyze audiences to improve reach and engagement',
        'about.do_4': 'Use automation and AI tools to streamline workflows and decision-making',
        'about.why_title': 'Why Work With Me',
        'about.why_1': 'Over 2 years of hands-on LinkedIn growth experience',
        'about.why_2': 'Proven results in visibility, engagement, and positioning',
        'about.why_3': 'Structured, goal-oriented approach (no random posting)',
        'about.why_4': 'Combination of marketing experience and AI development skills',

        'contact.title': 'Contact',
        'contact.subtitle': 'Ready to grow your LinkedIn presence with a clear and efficient approach?',

        'certs.title': 'Certifications',
        'certs.badge': 'Validation & Expertise',
        'certs.machine_learning': 'Machine Learning & AI Engineer',
        'certs.social_media': 'Social Media',
        'certs.content_marketing': 'Content Marketing',
        'certs.digital_marketing': 'Digital Marketing',
        'certs.seo': 'SEO',
        'certs.social_media_marketing': 'Social Media Marketing',
        'certs.python': 'Python 3',

        'contact.whatsapp': 'WhatsApp',
        'contact.send_msg': 'Send Message',
        'contact.email': 'Email',
        'contact.get_in_touch': 'Get in Touch',
        'contact.linkedin_profile': 'LinkedIn Profile',
        'contact.connect': 'Connect with Youness',
        'contact.rights': 'ALL SYSTEMS OPTIMIZED',
    },
    FR: {
        'nav.home': 'Accueil',
        'nav.profile': 'Profil',
        'nav.section': 'Section',
        'nav.about': 'À Propos',
        'nav.contact': 'Contact',
        'nav.experience': 'Expérience',
        'nav.education': 'Formation',
        'nav.skills': 'Compétences',
        'nav.projects': 'Projets',
        'nav.linkedin_freelancing': 'Freelance LinkedIn',
        'nav.ai_projects': 'Systèmes IA & Projets',
        'nav.certifications': 'Certifications',
        'btn.download_cv': 'Télécharger CV',

        'hero.system_mode': 'MODE SYSTÈME · ACTIF',
        'hero.title_1_p1':'Je vous aide ',
        'hero.title_1_p2':'à obtenir visibilité',
        'hero.title_2_p1':'leads et résultats ',
        'hero.title_2_p2':'sur Linkedin',
        'hero.subtitle': 'Transformez LinkedIn en un canal de croissance puissant.',
        'hero.ai_action': 'Ligne d\'Action IA',
        'hero.ai_diff': 'Propulsé par une automatisation intelligente et des systèmes d\'IA pour optimiser le contenu, les flux de travail et les décisions.',
        'hero.cta_contact': 'Contactez-moi',

        'linkedin.badge': 'Niveau de Service : Premium',
        'linkedin.title': 'Système de Croissance LinkedIn',
        'linkedin.subtitle': 'Un cadre structuré pour renforcer la visibilité, l\'autorité et la croissance des petites entreprises sur LinkedIn.',
        'linkedin.strat_1_title': 'Croissance de l\'Audience',
        'linkedin.strat_1_desc': 'Élargir votre portée auprès de prospects qualifiés et de leaders du secteur.',
        'linkedin.strat_2_title': 'Stratégie de Contenu',
        'linkedin.strat_2_desc': 'Conception narrative basée sur les données qui vous positionne comme leader d\'opinion.',
        'linkedin.strat_3_title': 'Optimisation du Profil',
        'linkedin.strat_3_desc': 'Transformer les visites en rendez-vous grâce à un copywriting performant.',
        'linkedin.strat_4_title': 'Positionnement de Marque',
        'linkedin.strat_4_desc': 'Différenciation stratégique dans un marché numérique saturé.',
        'linkedin.step': 'Étape',
        'linkedin.step_1': 'Analyse',
        'linkedin.step_2': 'Stratégie',
        'linkedin.step_3': 'Exécution',
        'linkedin.step_4': 'Optimisation',
        'linkedin.examples_title': 'Exemples de Travail',
        'linkedin.examples_subtitle': 'Stratégies éprouvées et résultats réels de campagnes de croissance LinkedIn réussies.',
        'linkedin.example_1_title': 'Création de Contenu LinkedIn',
        'linkedin.example_1_subtitle': 'Création de Contenu LinkedIn (Mots-Clés & Sujets)',
        'linkedin.example_1_desc': 'Création de contenus LinkedIn basés sur des mots-clés stratégiques et des sujets à forte demande, conçus pour maximiser la visibilité, l’engagement et la portée organique.',
        'linkedin.example_1_res': '100k+ Impressions',
        'linkedin.example_2_title': 'Profil LinkedIn Optimisé',
        'linkedin.example_2_subtitle': 'Optimisation de Profil LinkedIn (Section par Section)',
        'linkedin.example_2_desc': 'Optimisation complète du profil LinkedIn — headline, about, expérience et visuels — pour améliorer la clarté, la crédibilité et la conversion.',
        'linkedin.example_2_res': 'Qualité Premium',
        'linkedin.example_3_title': 'Croissance & Visibilité Stratégique',
        'linkedin.example_3_desc': 'Développement d’une audience de 0 à 40K grâce à une stratégie de contenu structurée, orientée visibilité, cohérence et croissance durable.',
        'linkedin.example_3_res': '40k+ Croissance',
        'linkedin.view_cta': 'VOIR UNIQUEMENT',
        'linkedin.growth_case': 'Cas de Croissance',

        'ai.badge': 'Module : Systèmes Intelligents',
        'ai.title': 'Systèmes IA & Agents Intelligents',
        'ai.subtitle': 'Ingénierie de solutions techniques, propres et crédibles via une implémentation IA sérieuse.',
        'ai.cap_1': 'Agents IA',
        'ai.cap_2': 'Systèmes Multi-Agents',
        'ai.cap_3': 'RAG',
        'ai.cap_4': 'Machine Learning',
        'ai.cap_5': 'Automatisation',
        'ai.proj_prefix': 'Projet',
        'ai.stack': 'Stack',

        'timeline.exp_title': 'Expérience Professionnelle',
        'timeline.edu_title': 'Formation',
        'timeline.exp_1_title': 'Freelance LinkedIn & Stratège Marketing Digital',
        'timeline.exp_1_company': 'Auto-entrepreneur',
        'timeline.exp_1_period': '2022 - Présent',
        'timeline.exp_1_desc': 'Développement et exécution de stratégies de croissance pour les fondateurs et entreprises B2B.',
        'timeline.exp_2_title': 'Cadre des Services Économiques et Sociaux',
        'timeline.exp_2_company': 'Secteur Public',
        'timeline.exp_2_period': 'Précédent',
        'timeline.exp_2_desc': 'Gestion des opérations sociales administratives et stratégiques avec focus sur la précision des données.',
        'timeline.exp_3_title': 'Stages (TGR, Banque Populaire)',
        'timeline.exp_3_company': 'Plusieurs Entités',
        'timeline.exp_3_period': 'Début de carrière',
        'timeline.exp_3_desc': 'Acquisition d\'une expérience fondamentale dans les services financiers et les opérations du Trésor public.',
        'timeline.edu_1_title': 'Développement IA',
        'timeline.edu_1_school': 'JobInTech / SUPMIR Academy',
        'timeline.edu_1_period': '02-2026',
        'timeline.edu_1_desc': 'Spécialisation en Agents Intelligents, LLMs et Automatisation de Systèmes.',
        'timeline.edu_2_title': 'Licence en Économie et Gestion',
        'timeline.edu_2_school': 'Université',
        'timeline.edu_2_period': '2019',
        'timeline.edu_2_desc': 'Fondation théorique et pratique des dynamiques d\'entreprise et de la modélisation économique.',
        'timeline.certs_title': 'Aperçu des Certifications',
        'timeline.cert_1': 'Spécialiste IA & Technologie',
        'timeline.cert_2': 'Marketing Digital & Analytics',
        'timeline.cert_3': 'Outils de Projet Professionnels',

        'skills.badge': 'Compétences Clés',
        'skills.title': 'Stack Technique & Stratégique',
        'skills.group_1': 'Marketing Digital & LinkedIn',
        'skills.group_2': 'IA & Systèmes Intelligents',
        'skills.group_3': 'Outils Techniques & de Projet',
        'skills.g1_1': "Croissance de l'Audience",
        'skills.g1_2': 'Stratégie de Contenu',
        'skills.g1_3': 'Optimisation de Profil',
        'skills.g1_4': 'Génération de Leads B2B',
        'skills.g1_5': 'Google Analytics',
        'skills.g2_1': 'Agents IA',
        'skills.g2_2': 'Systèmes Multi-Agents',
        'skills.g2_3': 'RAG & LLMs',
        'skills.g2_4': 'Machine Learning',
        'skills.g2_5': 'Automatisation de Flux',
        'skills.g3_1': 'Jira & Méthode Agile',
        'skills.g3_2': 'Planification Stratégique',
        'skills.g3_3': 'Analyse de Données',
        'skills.g3_4': 'Python/TypeScript',
        'skills.g3_5': 'React/Node.js',

        'about.mission_title': 'Ma Mission',
        'about.mission_desc': 'Aider les petites entreprises, les entrepreneurs et les professionnels à accroître leur visibilité et leur audience sur LinkedIn grâce à des stratégies claires, une exécution constante et une utilisation intelligente de l\'automatisation et des systèmes d\'IA.',
        'about.do_title': 'Ce que je fais pour mes clients',
        'about.do_1': 'Construire et optimiser des profils LinkedIn et des pages d\'entreprise',
        'about.do_2': 'Créer et gérer du contenu aligné avec les objectifs commerciaux',
        'about.do_3': 'Analyser les audiences pour améliorer la portée et l\'engagement',
        'about.do_4': 'Utiliser des outils d\'automatisation et d\'IA pour simplifier les flux de travail et la prise de décision',
        'about.why_title': 'Pourquoi travailler avec moi',
        'about.why_1': 'Plus de 2 ans d\'expérience concrète en croissance LinkedIn',
        'about.why_2': 'Résultats prouvés en visibilité, engagement et positionnement',
        'about.why_3': 'Approche structurée et orientée vers les objectifs (pas de publications aléatoires)',
        'about.why_4': "Combinaison d'expérience marketing et de compétences en développement d'IA",

        'contact.title': 'Contact',
        'contact.subtitle': 'Prêt à développer votre présence sur LinkedIn avec une approche claire et efficace ?',

        'certs.title': 'Certifications',
        'certs.badge': 'Validation & Expertise',
        'certs.machine_learning': 'Ingénieur Machine Learning & IA',
        'certs.social_media': 'Réseaux Sociaux',
        'certs.content_marketing': 'Marketing de Contenu',
        'certs.digital_marketing': 'Marketing Digital',
        'certs.seo': 'Référencement Naturel (SEO)',
        'certs.social_media_marketing': 'Marketing des Réseaux Sociaux',
        'certs.python': 'Python 3',

        'contact.whatsapp': 'WhatsApp',
        'contact.send_msg': 'Envoyer un message',
        'contact.email': 'Email',
        'contact.get_in_touch': 'Entrer en contact',
        'contact.linkedin_profile': 'Profil LinkedIn',
        'contact.connect': 'Se connecter avec Youness',
        'contact.rights': 'TOUS SYSTÈMES OPTIMISÉS',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [lang, setLang] = useState<Language>('EN');

    const t = (key: string) => {
        return translations[lang][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};
